### ISSUE TITLE
Building this DPDK fails

### ISSUE THREAD

**Issue by georgii-t** [nic-bench/dpdk#2]
Hi, sorry for naïve question but how to build this DPDK? the build process fails for me with some linking error, looks like I'm missing some Mellanox libraries as prerequisites. I tried installing MLNX OFED driver but was not able to get around the error. My build process that works with upstream DPDK is just
meson build
ninja -C build

error log is as follows including warnings: 
../drivers/common/mlx5/linux/mlx5_glue.c: In function ‘mlx5_glue_dv_update_flow’:
../drivers/common/mlx5/linux/mlx5_glue.c:626:9: warning: implicit declaration of function ‘mlx5dv_dr_rule_update’; did you mean ‘mlx5dv_dr_rule_create’? [-Wimplicit-function-declaration]
  626 |  return mlx5dv_dr_rule_update(flow_id, match_value, num_actions,
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         mlx5dv_dr_rule_create
../drivers/common/mlx5/linux/mlx5_glue.c:626:9: warning: nested extern declaration of ‘mlx5dv_dr_rule_update’ [-Wnested-externs]
[1135/2635] Compiling C object 'drivers/a715181@@tmp_rte_net_mlx5@sta/net_mlx5_mlx5_flow.c.o'.
../drivers/net/mlx5/mlx5_flow.c: In function ‘flow_drv_update’:
../drivers/net/mlx5/mlx5_flow.c:5600:20: warning: unused variable ‘priv’ [-Wunused-variable]
 5600 |  struct mlx5_priv *priv = dev->data->dev_private;
      |                    ^~~~
../drivers/net/mlx5/mlx5_flow.c:5596:34: warning: unused parameter ‘actions’ [-Wunused-parameter]
 5596 |    const struct rte_flow_action *actions,
      |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
../drivers/net/mlx5/mlx5_flow.c: In function ‘mlx5_flow_update’:
../drivers/net/mlx5/mlx5_flow.c:5640:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 5640 |     if (!in_flow)
      |     ^~
../drivers/net/mlx5/mlx5_flow.c:5642:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 5642 |  ret = flow_drv_update(dev, in_flow, items, actions, error);
      |  ^~~
[1340/2635] Linking target drivers/librte_common_mlx5.so.21.0.
FAILED: drivers/librte_common_mlx5.so.21.0 
cc  -o drivers/librte_common_mlx5.so.21.0 'drivers/a715181@@rte_common_mlx5@sha/meson-generated_.._rte_common_mlx5.pmd.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_devx_cmds.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_common.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_common_mp.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_common_mr.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_malloc.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_mlx5_common_pci.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_linux_mlx5_nl.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_linux_mlx5_common_os.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_linux_mlx5_common_verbs.c.o' 'drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_linux_mlx5_glue.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,librte_common_mlx5.so.21 -Wl,--no-as-needed -pthread -lm -ldl -lnuma lib/librte_hash.so.21.0 lib/librte_eal.so.21.0 lib/librte_kvargs.so.21.0 lib/librte_telemetry.so.21.0 lib/librte_ring.so.21.0 lib/librte_rcu.so.21.0 lib/librte_pci.so.21.0 drivers/librte_bus_pci.so.21.0 lib/librte_net.so.21.0 lib/librte_mbuf.so.21.0 lib/librte_mempool.so.21.0 -Wl,--version-script=/root/dpdk/drivers/common/mlx5/version.map /usr/lib/x86_64-linux-gnu/libmlx5.so /usr/lib/x86_64-linux-gnu/libibverbs.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/../lib:$ORIGIN/' -Wl,-rpath-link,/root/dpdk/build/lib -Wl,-rpath-link,/root/dpdk/build/drivers
/usr/bin/ld: drivers/a715181@@tmp_rte_common_mlx5@sta/common_mlx5_linux_mlx5_glue.c.o: in function `mlx5_glue_dv_update_flow':
mlx5_glue.c:(.text+0x6c7): undefined reference to `mlx5dv_dr_rule_update'
collect2: error: ld returned 1 exit status

Thank you very much for your attention.

**Comment by tbarbette** [comment]
Hi @georgii-t !

We forgot to say (and push!) that the backing RDMA-CORE with the support of the related update verbs was also needed. It's available at https://github.com/nic-bench/rdma-core.

No need to replace your system's RDMA-CORE, you can compile that rdma-core without installing, then build DPDK with:
```
export PKG_CONFIG_PATH=/home/tom/workspace/rdma-core/install/usr/local/lib/pkgconfig/ 
export LD_LIBRARY_PATH=/home/tom/workspace/rdma-core/install/usr/local/lib/ 
ldconfig
meson -Dprefix=$(pwd)/install/ -Ddisable_drivers=mlx4,net/mlx4 build
cd build
ninja
ninja install
```

Similarly when building something with that DPDK, you'll need to add the path of this DPDK (the install folder) in LD_LIBRARY_PATH, and this DPDK's pkgconfig in PKG_CONFIG_PATH too
